/**
 * CD
 * Gives all the details of the CDs
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface CD {
    id?: number;

    identification: string;

    name: string;

    description?: string;

    imagePath?: string;

    unitCost: number;

}
