@startuml

actor :Anonymous: as actorAnonym

usecase (Browse CD catalog) as ucBrowseCD
usecase (Browse Book catalog) as ucBrowseBook
usecase (Browse DVD catalog) as ucBrowseDVD

actorAnonym --> ucBrowseCD
actorAnonym ---> ucBrowseBook
actorAnonym --> ucBrowseDVD

newpage

actor :Customer: as actorCustomer

usecase (Login) as ucLogin
usecase (Logout) as ucLogout
usecase (Browse and update profile) as ucProfile
usecase (Add item \n to shopping cart) as ucAddCart
usecase (Browse shopping \n cart content) as ucBrowseCart
usecase (Checkout) as ucCheckout
usecase (Update inventory) as ucInventory

actorCustomer --> ucLogin
actorCustomer --> ucLogout
actorCustomer ---> ucProfile
actorCustomer --> ucAddCart
actorCustomer --> ucBrowseCart
actorCustomer -> ucCheckout

ucCheckout .> ucInventory

newpage

actor :Administrator: as actorAdmin

usecase (CRUD CD catalog) as ucCRUDCD
usecase (CRUD Book catalog) as ucCRUDBook
usecase (CRUD DVD catalog) as ucCRUDDVD
usecase (Generate ISBN, UPC, \n EAN and GS1 numbers) as ucGenerate
usecase (Update inventory) as ucInventory
usecase (Browse inventory) as ucBrowseInventory

actorAdmin --> ucCRUDCD
actorAdmin --> ucCRUDBook
actorAdmin --> ucCRUDDVD
actorAdmin --> ucBrowseInventory

ucCRUDCD ..> ucGenerate
ucCRUDBook ..> ucGenerate
ucCRUDDVD ..> ucGenerate

ucCRUDCD ...> ucInventory
ucCRUDBook ...> ucInventory
ucCRUDDVD ...> ucInventory

@enduml