/**
 * Book API
 * Operations for Books.
 *
 * OpenAPI spec version: 02
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export const enum Genre {
  'Science fiction',
  'Satire',
  'Drama',
  'Action and Adventure',
  'Romance',
  'Mystery',
  'Horror',
  'Self help',
  'Health',
  'Guide',
  'Travel',
  'Children',
  'Science',
  'History',
  'Math',
  'Anthology',
  'Poetry',
  'Encyclopedias',
  'Dictionaries',
  'Comics',
  'Art',
  'Cookbooks',
  'Diaries',
  'Journals',
  'Series',
  'Trilogy',
  'Biographies',
  'Autobiographies',
  'Fantasy'
}

export class Book {
  constructor(
    public id?: number,
    public title?: string,
    public author?: string,
    public year?: number,
    public genre?: Genre,
    public isbn?: string,
  ) {
  }
}
