/**
 * Book API
 * Operations for Books.
 *
 * OpenAPI spec version: 02
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export const enum Genre {
  'JAZZ',
  'ROCK',
  'FOLK',
  'POP',
  'BLUES',
  'HIP_HOP',
  'RAPPING',
  'COUNTRY',
  'PUNK_ROCK',
  'RHYTHM_AND_BLUES',
  'ELECTRONIC_DANCE',
  'SINGING',
  'REGGAE',
  'POPULAR',
  'DISCO',
  'FUNK',
  'SOUL',
  'TECHNO',
  'CLASSICAL_PERIOD',
  'ALTERNATIVE_ROCK',
  'CLASSICAL',
  'INSTRUMENTAL',
  'HOUSE',
  'DUBSTEP'
}

export class Book {
  constructor(
    public id?: number,
    public title?: string,
    public author?: string,
    public year?: number,
    public genre?: Genre,
    public isbn?: string,
  ) {
  }
}
