/**
 * Book API
 * Operations for Books.
 *
 * OpenAPI spec version: 02
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Book {
    id?: number;

    author?: string;

    title?: string;

    year?: number;

    genre?: string;

    isbn?: string;

}
