@startuml

node "Raspberry PI" as piclient {
    artifact "Angular APP" <<NGINX>> as angular
}

node "pi-grom-server-01" as piserver {
    artifact "Number API" <<Wildfly Swarm>> as numberapi
}

angular -> numberapi: "     HTTP      "
@enduml
