@startuml

node "Raspberry PI" as piclient {
    artifact "Angular APP" <<NGINX>> as angular
}

node "pi-grom-server-01" as piserver {
    artifact "Number API" <<Wildfly Swarm>> as numberapi
}

node "pi-grom-server-02" as piserver2 {
    artifact "Book API" <<TomEE>> as bookapi
}

node "Raspberry PI" as piregistry {
    artifact "Eureka" <<Tomcat>> as eureka
}

node "Mac" as mac {
    artifact "ELK" as elk
}

angular -> bookapi: "     HTTP      "
bookapi -> numberapi: "     HTTP      "
bookapi -.> elk: "     Logs      "
numberapi -.> elk: "     Logs      "
numberapi -up.> eureka: "     Registers      "
bookapi -up.> eureka: "     Registers/Lookup      "
angular -up.> eureka: "     Lookup      "
@enduml
