@startuml

node "Raspberry PI" as piclient {
    artifact "Angular APP" as angular
}

node "Raspberry PI" as piserver {
    artifact "Number API" as numberapi
}

node "Raspberry PI" as piserver2 {
    artifact "Book API" as bookapi
}

angular -> numberapi: "     HTTP      "
numberapi -> bookapi: "     HTTP      "
@enduml
