@startuml

node "pi-client-01" as piclient #grey {
    artifact "Angular APP" <<NGINX>> as angular #white
}

node "pi-grom-server-01" as piserver #orange {
    artifact "Number API" <<Wildfly Swarm>> as numberapi #white
}

node "pi-grom-load-balancer" as piserver2 #red {
    artifact "Book API" <<TomEE>> as bookapi #white
}

node "pi-grom-database" as piregistry #purple {
    artifact "Consul" as consule #white
}

node "Mac" as mac {
    artifact "ELK" as elk
}

angular -> bookapi: "     HTTP      "
bookapi -> numberapi: "     HTTP      "
bookapi -.> elk: "     Logs      "
numberapi -.> elk: "     Logs      "
piclient -.> elk: "     Logs      "
consule -.> elk: "     Logs      "
numberapi -up.> consule: "     Registers      "
bookapi -up.> consule: "     Registers/Lookup      "
angular -up.> consule: "     Lookup      "
@enduml
